HOSTS:
  master:
    roles:
      - master
      - agent
      - default
      - dashboard
      - database
    platform: el-7-x86_64
    box: puppetlabs/centos-7.0-64-nocm
    ip: 10.10.0.10
    vagrant_memsize: 8192
    box_url: https://vagrantcloud.com/puppetlabs/boxes/centos-7.0-64-nocm
    hypervisor: vagrant
CONFIG:
  log_level: verbose
  type: foss
